### ISSUE TITLE
代码有误

### ISSUE THREAD

**Issue by AllanChen** [Louiszhai/Louiszhai.github.io#11]
文章：http://louiszhai.github.io/2017/03/12/promise/#catch
代码段：
`//params: String
Promise.reject('该prormise已被拒绝');
.catch(function(reason){
  console.log('catch:', reason);
});`
会出编译错误，错误是多了个“;”
感谢作者，promise 的文章很精彩

**Comment by Louiszhai** [comment]
感谢指正，已更新~
