### ISSUE TITLE
深度长文】JavaScript数组所有API全解密 错误

### ISSUE THREAD

**Issue by dream2023** [Louiszhai/Louiszhai.github.io#12]
http://louiszhai.github.io/2017/04/28/array
```js
//  错误示例
Array.of(8.0); // [8]
Array(8.0); // [undefined × 8]
```

```js
// 正确
Array.of(8.0); // [8]
Array(8.0); // [empty × 8]
```
参考：
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/of

**Comment by Louiszhai** [comment]
感谢指正，已更新。之前chrome输出的undefined，可能是后面升级后更新了
