### ISSUE TITLE
关于fetch实现timeout疑问

### ISSUE THREAD

**Issue by yxc888** [Louiszhai/Louiszhai.github.io#15]
> url
- https://juejin.im/post/58fab787b123db444906b90c
> question
- timeout部分，timeout时间设置较长，成功fecth了之后，定时器还是会调用内部的abort，打印出abort done. 这个可以避免吗
- 能实现下retry这个功能吗

**Comment by Louiszhai** [comment]
问题1. 为什么会在成功fetch后，依然触发abort，可以在fetch成功回调时，取消定时器
问题2. retry可以自行实现的哈
