### ISSUE TITLE
JavaScript数组所有API全解密-sort() 方法之奇怪的chrome

### ISSUE THREAD

**Issue by sunmaer** [Louiszhai/Louiszhai.github.io#3]
您好，最近阅读了很多您的博客，知识点通俗易懂，收获颇多，很感谢您的分享。但是在尝试使用 的时候发现了一处小错误，特此告诉博主。

`var array = [{ n: "a", v: 1 }, { n: "b", v: 1 }, { n: "c", v: 1 }, { n: "d", v: 1 }, { n: "e", v: 1 }, { n: "f", v: 1 }, { n: "g", v: 1 }, { n: "h", v: 1 }, { n: "i", v: 1 }, { n: "j", v: 1 }, { n: "k", v: 1 }, ];

array.sort(function (a, b) {
	return a.v - b.v || array.indexOf(a)-array.indexOf(b);
});

for (var i = 0,len = array.length; i < len; i++) {
    console.log(array[i].n);
}

// a f c d e b g h i j k`

谷歌控制台运行上述代码后，数组排序后还是不稳定的。我百度了下，原因可能是数组的顺序一直在变化，所以indexOf()取得的位置不是原始的索引，从而导致了错误。

错误链接：[https://louiszhai.github.io/2017/04/28/array/#奇怪的chrome](url)

**Comment by chbro** [comment]
楼上说得对，排序过程中数组不断改变。可以增加一个字段记录原始位置
array.map((v, i) => v.index = i)
array.sort((a,b) => {
    return a.v-b.v || a.index - b.index;
})

**Comment by Louiszhai** [comment]
非常感谢@sunmaer和@chbro，是我没有考虑到。由于快速排序能够交换非相邻的两个元素，这样就势必导致值相同的元素相对位置变化，位置的变化就导致下标变化，这样indexOf实时取到的下标位置就无法反映出元素的初始位置，因此像indexOf这样依赖不稳定的下标是不可靠的。@chbro的方案就很好地解决了这个问题。
