### ISSUE TITLE
关于hexo博客的更新问题

### ISSUE THREAD

**Issue by robinson90** [Louiszhai/Louiszhai.github.io#5]
我也用hexo搭建了一个技术博客，但是发现在更新博客的时候很麻烦，每次都要吧整个项目down下来，然后做推送，之后也不方便做文章的分类管理，请问你是怎么操作这个的。

**Comment by Louiszhai** [comment]
_post目录下，新增markdown文件，然后hexo g打包，最后将改动直接push就好了，不明白直接down是什么意思？

**Comment by robinson90** [comment]
@Louiszhai 还是需要你把项目clone下来，然后操作新文件啊，然后不同分类的文章其实都在一个路径下的。既不是按照分类，也不是按照时间，特别不好查看和批量管理

**Comment by Louiszhai** [comment]
听起来感觉你可能不太熟悉hexo，hexo中写markdown文章，直接在其`source/_post`目录新增`*.md`即可，完成后`hexo g`打包编译，`hexo d`上传就行。
之所以能将打包到`public`目录的文件上传到github，主要是因为config.yml文件中包含如下配置：
![image](https://user-images.githubusercontent.com/8412301/31052506-064bfae6-a64c-11e7-9af6-ec72648ff4d5.png)
