### ISSUE TITLE
位运算文章关于异或使用段落有疑问,希望作者解疑

### ISSUE THREAD

**Issue by PlusLius** [Louiszhai/Louiszhai.github.io#7]
> 任意整数x与2的n次方进行按位异或运算, 若它的二进制补码形式的倒数第n+1位是1, 则返回 x-2的n次方, 反之若为0, 则返回 x+2的n次方 .

1.倒数n+1应该是从哪边开始数,n应该是多少?
2.能否提供具体的使用案例
3.文中它的二进制补码形式 它是指 a ^ b,指a呢还是指b

**Comment by Louiszhai** [comment]
> 任意整数x与2的n次方进行按位异或运算, 若它的二进制补码形式的倒数第n+1位是1, 则返回 x-2的n次方, 反之若为0, 则返回 x+2的n次方

这句我可能断句不太对，x -（2的n次方），2的n次方是一个整体，请结合理解下。
它的二进制补码形式指的是前面讲的任意整数x，对于如下案例而言，就是14 或 16。

我们来分析下：
  1. 倒数第n+1位，倒数是从右往左数，那么对于 `14^8` 这样的位运算，8便是2的3次方，n值为3，那么n+1就是倒数第4位，即从右往左数的第4位，对于14而言，其补码为`1110`，倒数第4位是1，应该减去8，那么最终结果套用以上公式得：`14^8 === 14-8 === 6`;
  2. 若14换成16，16的补码为`10000`，其倒数第4位是0，那么应该加上8，最终结果为24。
